name: Debian
on: [push, pull_request]
jobs:
  Debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: "./.github/workflows/debian.Dockerfile"
          tags: jamespfennell/goxz:latest
          push: false
